package com.nasnav.response;

/**
 * Hold Response Status constants
 */
public enum ResponseStatus {
    EMAIL_EXISTS,
    ACTIVATION_SENT,
    NEED_ACTIVATION,
    INVALID_EMAIL,
    INVALID_NAME,
    SYS_ERROR,
    INVALID_PARAMETERS,
    EMAIL_NOT_EXIST,
    INVALID_TOKEN,
    EXPIRED_TOKEN,
    INVALID_PASSWORD,
    INVALID_CREDENTIALS,
    ACCOUNT_SUSPENDED,
    INSUFFICIENT_RIGHTS,
    UNAUTHENTICATED,
    ACTIVATED,
    INVALID_ROLE,
    INVALID_STORE,
    INVALID_ORGANIZATION,
    INVALID_REDIRECT_URL;
}