variables:
  VERSION: "1.0"
  POSTGRES_DB: nasnav-tests
  POSTGRES_USER: nasnav
  POSTGRES_PASSWORD: nasnav
  POSTGRES_HOST_AUTH_METHOD: trust
  MAVEN_OPTS: "-Dmaven.repo.local=.m2"

cache:
  key: "$CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME"
  paths:
    - .m2/

stages:
  - test

test:maven:
  stage: test
  services:
    - postgres:15.2-alpine
  image: maven:3.8.6-openjdk-11
  script:
    - mvn --version
    - cp ./deploy/properties-test/* ./nasnav/src/main/resources/
    - cp ./deploy/properties-test/* ./yeshtery/src/main/resources/
    - mvn -B --no-transfer-progress test
  artifacts:
    when: always
    reports:
      junit:
        - nasnav/target/surefire-reports/TEST-*.xml
        - yeshtery/target/surefire-reports/TEST-*.xml
  tags:
    - meetusvr
    - docker
  only:
    - merge_requests
