variables:
  VERSION: "1.0"
  POSTGRES_DB: nasnav-tests
  POSTGRES_USER: nasnav
  POSTGRES_PASSWORD: nasnav
  POSTGRES_HOST_AUTH_METHOD: trust
  MAVEN_OPTS: "-Dmaven.repo.local=.m2"

cache:
  key: "$CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME"
  paths:
    - .m2/

stages:
  - test
  - compile
  - build
  - deploy

test:maven:
  stage: test
  services:
    - postgres:15.2-alpine
  image: maven:3.8.6-openjdk-11
  script:
    - mvn --version
    - cp ./deploy/properties-test/* ./nasnav/src/main/resources/
    - cp ./deploy/properties-test/* ./yeshtery/src/main/resources/
    - mvn -B --no-transfer-progress test
  artifacts:
    when: always
    reports:
      junit:
        - nasnav/target/surefire-reports/TEST-*.xml
        - yeshtery/target/surefire-reports/TEST-*.xml
  tags:
    - meetusvr
    - docker

build:compile:
  stage: compile
  image: docker:20.10.16
  script:
    - cp ./deploy/properties/*.properties ./nasnav/src/main/resources/
    - cp ./deploy/properties/*.properties ./yeshtery/src/main/resources/
    - sh ./deploy/docker_build.sh
  artifacts:
    reports:
      dotenv: build/env
  only:
    - develop
    - uat
    - prod
  tags:
    - meetusvr
    - docker

build:publish:
  image: docker:20.10.16
  stage: build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - sh ./deploy/docker_publish.sh
  only:
    - develop
    - uat
    - prod
  tags:
    - meetusvr
    - docker

deploy:
  stage: deploy
  trigger:
    project: meetusvr/devops
    branch: main
    strategy: depend
  variables:
    MEETUSVR_BACKEND_ENV: $CI_COMMIT_BRANCH
    MEETUSVR_BACKEND_IMAGE_TAG_FQN: $IMAGE_TAG_FQN
    UPSTREAM_PROJECT_PATH: $CI_PROJECT_PATH
  only:
    - develop
    # - uat
    # - prod
