package com.nasnav.persistence;
// Generated Mar 23, 2019 9:34:28 PM by Hibernate Tools 5.1.10.Final

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Type;

import com.nasnav.dto.BaseRepresentationObject;
import com.nasnav.dto.OrderRepresentationObject;

import lombok.Data;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name = "orders", schema = "public")
public class OrdersEntity {

	private Long id;
	private String address;
	private String email;
	private String name;
	private Integer paymentType;
	private Long userId;
	private Date createdAt;
	private Date updatedAt;
	private Date dateDelivery;
	private Long organizationId;
	private Integer status;
	@Column(name = "cancelation_reasons")
	@Type(type = "com.nasnav.persistence.GenericArrayType")
	private String[] cancelationReasons;
	private Long shopId;
	private String driverName;
	private Boolean equipped;
	private String basket;
	private BigDecimal amount;

	public OrdersEntity() {
	}

	public OrdersEntity(Long id, Date createdAt, Date updatedAt, String basket, BigDecimal amount) {
		this.id = id;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.basket = basket;
		this.amount = amount;
	}

	public OrdersEntity(Long id, String address, String email, String name, Integer paymentType, Long userId, Date createdAt,
			Date updatedAt, Date dateDelivery, Long organizationId, Integer status, String[] cancelationReasons,
			Long shopId, String driverName, Boolean equipped, String basket, BigDecimal amount) {
		this.id = id;
		this.address = address;
		this.email = email;
		this.name = name;
		this.paymentType = paymentType;
		this.userId = userId;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.dateDelivery = dateDelivery;
		this.organizationId = organizationId;
		this.status = status;
		this.cancelationReasons = cancelationReasons;
		this.shopId = shopId;
		this.driverName = driverName;
		this.equipped = equipped;
		this.basket = basket;
		this.amount = amount;
	}

	@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "address", length = 150)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "email", length = 40)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "name", length = 40)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "payment_type")
	public Integer getPaymentType() {
		return this.paymentType;
	}

	public void setPaymentType(Integer paymentType) {
		this.paymentType = paymentType;
	}

	@Column(name = "user_id")
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 29)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_delivery", length = 29)
	public Date getDateDelivery() {
		return this.dateDelivery;
	}

	public void setDateDelivery(Date dateDelivery) {
		this.dateDelivery = dateDelivery;
	}

	@Column(name = "organization_id")
	public Long getOrganizationId() {
		return this.organizationId;
	}

	public void setOrganizationId(Long organizationId) {
		this.organizationId = organizationId;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	/*
	@Column(name = "cancelation_reasons")
	
	public String[] getCancelationReasons() {
		return this.cancelationReasons;
	}

	@Type(type = "com.nasnav.persistence.GenericArrayType")
	public void setCancelationReasons(String[] cancelationReasons) {
		this.cancelationReasons = cancelationReasons;
	}
	*/

	@Column(name = "shop_id")
	public Long getShopId() {
		return this.shopId;
	}

	public void setShopId(Long shopId) {
		this.shopId = shopId;
	}

	@Column(name = "driver_name")
	public String getDriverName() {
		return this.driverName;
	}

	public void setDriverName(String driverName) {
		this.driverName = driverName;
	}

	@Column(name = "equipped")
	public Boolean getEquipped() {
		return this.equipped;
	}

	public void setEquipped(Boolean equipped) {
		this.equipped = equipped;
	}

	@Column(name = "basket", nullable = false)
	public String getBasket() {
		return this.basket;
	}

	public void setBasket(String basket) {
		this.basket = basket;
	}

	@Column(name = "amount", nullable = false, precision = 10)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}
/*
	@Override
	public BaseRepresentationObject getRepresentation() {
		OrderRepresentationObject representationObject = new OrderRepresentationObject();
		representationObject.setOrder_id(getId());
		representationObject.setPrice(getAmount());
		return representationObject;
	}
	*/

}
