package com.nasnav.persistence;
// Generated Mar 24, 2019 2:51:31 PM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Permissions generated by hbm2java
 */
@Entity
@Table(name = "permissions", schema = "public")
public class Permissions implements java.io.Serializable {

	private static final long serialVersionUID = 11548469958L;
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int id;
	private String targetModelName;
	private String action;
	private Date createdAt;
	private Date updatedAt;

	public Permissions() {
	}

	public Permissions(int id, Date createdAt, Date updatedAt) {
		this.id = id;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Permissions(int id, String targetModelName, String action, Date createdAt, Date updatedAt) {
		this.id = id;
		this.targetModelName = targetModelName;
		this.action = action;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "target_model_name")
	public String getTargetModelName() {
		return this.targetModelName;
	}

	public void setTargetModelName(String targetModelName) {
		this.targetModelName = targetModelName;
	}

	@Column(name = "action")
	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 29)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
