package com.nasnav.persistence;
// Generated Mar 24, 2019 2:51:31 PM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Products generated by hbm2java
 */
//@Entity
//@Table(name = "products", schema = "public")
//TODO stockses fails and it's redandunt with ProductEntity
public class Products implements java.io.Serializable {

	private long id;
	private String name;
	private String PName;
	private String description;
	private String coverImage;
	private Boolean infoUpdated;
	private Long brandId;
	private Long categoryId;
	private Long organizationId;
	private Date createdAt;
	private Date updatedAt;
	private String itemId;
	private String barcode;
	private Set<StocksEntity> stockses = new HashSet<StocksEntity>(0);

	public Products() {
	}

	public Products(long id, Date createdAt, Date updatedAt) {
		this.id = id;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Products(long id, String name, String PName, String description, String coverImage, Boolean infoUpdated,
			Long brandId, Long categoryId, Long organizationId, Date createdAt, Date updatedAt, String itemId,
			String barcode, Set<StocksEntity> stockses) {
		this.id = id;
		this.name = name;
		this.PName = PName;
		this.description = description;
		this.coverImage = coverImage;
		this.infoUpdated = infoUpdated;
		this.brandId = brandId;
		this.categoryId = categoryId;
		this.organizationId = organizationId;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.itemId = itemId;
		this.barcode = barcode;
		this.stockses = stockses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "p_name")
	public String getPName() {
		return this.PName;
	}

	public void setPName(String PName) {
		this.PName = PName;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "cover_image")
	public String getCoverImage() {
		return this.coverImage;
	}

	public void setCoverImage(String coverImage) {
		this.coverImage = coverImage;
	}

	@Column(name = "info_updated")
	public Boolean getInfoUpdated() {
		return this.infoUpdated;
	}

	public void setInfoUpdated(Boolean infoUpdated) {
		this.infoUpdated = infoUpdated;
	}

	@Column(name = "brand_id")
	public Long getBrandId() {
		return this.brandId;
	}

	public void setBrandId(Long brandId) {
		this.brandId = brandId;
	}

	@Column(name = "category_id")
	public Long getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "organization_id")
	public Long getOrganizationId() {
		return this.organizationId;
	}

	public void setOrganizationId(Long organizationId) {
		this.organizationId = organizationId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 29)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "item_id")
	public String getItemId() {
		return this.itemId;
	}

	public void setItemId(String itemId) {
		this.itemId = itemId;
	}

	@Column(name = "barcode")
	public String getBarcode() {
		return this.barcode;
	}

	public void setBarcode(String barcode) {
		this.barcode = barcode;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "products")
	public Set<StocksEntity> getStockses() {
		return this.stockses;
	}

	public void setStockses(Set<StocksEntity> stockses) {
		this.stockses = stockses;
	}

}
