package com.nasnav.persistence;
// Generated Mar 24, 2019 2:51:31 PM by Hibernate Tools 5.1.10.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Roles generated by hbm2java
 */
@Entity
@Table(name = "roles", schema = "public")
public class Roles implements java.io.Serializable {

	private static final long serialVersionUID = 154487859L;
	
	private int id;
	private String name;
	private Long organizationId;

	public Roles() {
	}

	public Roles(int id) {
		this.id = id;
	}

	public Roles(int id, String name, Long organizationId) {
		this.id = id;
		this.name = name;
		this.organizationId = organizationId;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "organization_id")
	public Long getOrganizationId() {
		return this.organizationId;
	}

	public void setOrganizationId(Long organizationId) {
		this.organizationId = organizationId;
	}

}
