package com.nasnav.persistence;
// Generated Mar 24, 2019 2:51:31 PM by Hibernate Tools 5.1.10.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Stocks generated by hbm2java
 */
@Entity
@Table(name = "stocks", schema = "public")
public class StocksEntity implements java.io.Serializable {

	private long id;
	private Products products;
	private ShopsEntity shops;
	private Integer quantity;
	private String location;
	private Date createdAt;
	private Date updatedAt;
	private Long organizationId;
	private BigDecimal price;
	private BigDecimal discount;
	private Long subProductId;
	private Long variantId;

	public StocksEntity() {
	}

	public StocksEntity(long id, Date createdAt, Date updatedAt) {
		this.id = id;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public StocksEntity(long id, Products products, ShopsEntity shops, Integer quantity, String location, Date createdAt,
			Date updatedAt, Long organizationId, BigDecimal price, BigDecimal discount, Long subProductId,
			Long variantId) {
		this.id = id;
		this.products = products;
		this.shops = shops;
		this.quantity = quantity;
		this.location = location;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.organizationId = organizationId;
		this.price = price;
		this.discount = discount;
		this.subProductId = subProductId;
		this.variantId = variantId;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id")
	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "shop_id")
	public ShopsEntity getShops() {
		return this.shops;
	}

	public void setShops(ShopsEntity shops) {
		this.shops = shops;
	}

	@Column(name = "quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@Column(name = "location")
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 29)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "organization_id")
	public Long getOrganizationId() {
		return this.organizationId;
	}

	public void setOrganizationId(Long organizationId) {
		this.organizationId = organizationId;
	}

	@Column(name = "price", precision = 10)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "discount", precision = 10)
	public BigDecimal getDiscount() {
		return this.discount;
	}

	public void setDiscount(BigDecimal discount) {
		this.discount = discount;
	}

	@Column(name = "sub_product_id")
	public Long getSubProductId() {
		return this.subProductId;
	}

	public void setSubProductId(Long subProductId) {
		this.subProductId = subProductId;
	}

	@Column(name = "variant_id")
	public Long getVariantId() {
		return this.variantId;
	}

	public void setVariantId(Long variantId) {
		this.variantId = variantId;
	}

}
