package com.nasnav.enumerations;

public enum NotificationType {
	GENERIC,
	USER_QUEUE_UPDATES,
	ORGANIZATION_QUEUE_UPDATES ,
	RESERVE_AVAILABILITY ,
	START_CALL ,
	REJECT_CALL ,

	SCRAPPING_RESPONSE,
	IMPORT_DATA_PROCESS_UPDATE
}
