INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'GEMMA', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'ROYAL', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'INNOVA', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'SALLABCO', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'PRIMA', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'DURAVIT', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'TIB', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'IDEAL STANDARD', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'MASR ACRYLIC', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'ROCA', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'HANS GROHE', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'CERPA', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'RYLONDA', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'CLEOPATRA', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'SANY ACRLIC', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'GROHE', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'ZS', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'BEROIA', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'REMAS', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'TULIP', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'LECICO', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'KALLY', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'DUNE', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'ART', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'ZED', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'DFINESS', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'SARRAGUEMIN', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'Granito', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'GLORIA', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'DIAMOND ROCK', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'MURANO', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'ATLANTIC', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'HANS', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'ARCANA', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'Baoding', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'Aparici', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'NEWKER', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'KOHLER', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'ALFA', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'ATLAS CONCORDE', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'PORCELLAN', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'SSWW', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'IMAGE', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'VALENCIA', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'ARASEMCO', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'MOSAVIT', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'SARR DESIGN', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'GWAD', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'FRANKE', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'JOYU', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'MATERIAL', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'COLORKER', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'HONG YU', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'VENUS', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'CONI', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'PRIME GROUP', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'FILLI FRATTINI', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'ROMARIO', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'ALTO GLASS', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'MIJARES', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'MARAZZI', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'APE', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'AL-AMAN', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'KITCHEN STUDIO', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'WD', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'DREAM TILE', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'yekalon', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'INTERHASA', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'LIMESTONE', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'VAMA', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'LANGDENG', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'CERA', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'TAU', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'GEOTILES', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'ARGENTA', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'CICOGRES', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'ECOCERAMIC', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'kito', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'LA FABBRICA', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'LOSDI', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'REDRING', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'AOXIN', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'Avilados', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'Gazella', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'Vivo', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'UKINOX', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'PELI PARQUET', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'WOMA', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'PORCELANITE DOS', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'ASFOUR CRYSTAL', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'Glass Design', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'OSET', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'VIEWGRES', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'LANKEE', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'BATHCO', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'WIDING', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'ALAPLANA', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'MEXDA', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'LUIS VALENTINO', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'REGALIA', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'GRAVENA', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'ONIX', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'RUBEX', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'MAINZU', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'ABK', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'HDC', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'FLORINA', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'SIEMENS', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'KERABEN', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'MMT-STONE', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'HUIDA', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'GAYAFORES', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'PLATERA', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'PLAZA', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'TERCOCER', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'SEM', 99001);
INSERT INTO public.brands(category_id, name, organization_id) VALUES ( 201, 'KLUDI', 99001);