INSERT INTO public.categories(id, name, created_at, updated_at) VALUES(233, 'COLLECTION2'	, now(), now());



--INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'CERAMIC'	,'CERAMIC' , 'CERAMIC', '{}', 0, 99001);
--INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'ROYAL'	,'ROYAL' , 'ROYAL', '{}', 0, 99001);
--INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'FLOOR'	,'FLOOR' , 'FLOOR', '{}', 0, 99001);


INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, '13414'	,'13414' , '13414', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, '13620'	,'13620' , '13620', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, '27384'	,'27384' , '27384', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, '27412'	,'27412' , '27412', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, '27413'	,'27413' , '27413', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, '27454'	,'27454' , '27454', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, '27505'	,'27505' , '27505', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, '31494'	,'31494' , '31494', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, '32129'	,'32129' , '32129', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, '41000'	,'41000' , '41000', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, '71220'	,'71220' , '71220', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, '134230'	,'134230' , '134230', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, '714100'	,'714100' , '714100', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, '3174118'	,'3174118' , '3174118', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, '111815001'	,'111815001' , '111815001', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, '115035211'	,'115035211' , '115035211', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, '115040211'	,'115040211' , '115040211', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, '115045211'	,'115045211' , '115045211', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, '115055211'	,'115055211' , '115055211', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, '115120111'	,'115120111' , '115120111', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, '115120211'	,'115120211' , '115120211', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, '115120461'	,'115120461' , '115120461', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, '115125111'	,'115125111' , '115125111', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, '115125211'	,'115125211' , '115125211', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, '115125461'	,'115125461' , '115125461', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, '115130111'	,'115130111' , '115130111', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, '115130211'	,'115130211' , '115130211', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, '115130461'	,'115130461' , '115130461', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, '115135111'	,'115135111' , '115135111', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, '115135211'	,'115135211' , '115135211', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, '115135461'	,'115135461' , '115135461', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, '115770111'	,'115770111' , '115770111', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, '115770211'	,'115770211' , '115770211', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, '115770461'	,'115770461' , '115770461', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, '115777111'	,'115777111' , '115777111', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, '115777211'	,'115777211' , '115777211', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, '115777461'	,'115777461' , '115777461', '{}', 0, 99001);

INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'DÉCOR'	,'DÉCOR' , 'DÉCOR', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'PORCELAIN'	,'PORCELAIN' , 'PORCELAIN', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'BIDET'	,'BIDET' , 'BIDET', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'BASIN'	,'BASIN' , 'BASIN', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'JACUZZI'	,'JACUZZI' , 'JACUZZI', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'URINAL'	,'URINAL' , 'URINAL', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'BATHTUB'	,'BATHTUB' , 'BATHTUB', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'KITCHEN SINK'	,'KITCHEN SINK' , 'KITCHEN SINK', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'SWIMMING POOL'	,'SWIMMING POOL' , 'SWIMMING POOL', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'MIXERS'	,'MIXERS' , 'MIXERS', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'COMBINATION'	,'COMBINATION' , 'COMBINATION', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'ACCESSORIES'	,'ACCESSORIES' , 'ACCESSORIES', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'BUILT IN CISTERNS'	,'BUILT IN CISTERNS' , 'BUILT IN CISTERNS', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'FURNITURE'	,'FURNITURE' , 'FURNITURE', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'STONE'	,'STONE' , 'STONE', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'CABINET'	,'CABINET' , 'CABINET', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'HEATER'	,'HEATER' , 'HEATER', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'HDF'	,'HDF' , 'HDF', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'KITCHEN'	,'KITCHEN' , 'KITCHEN', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'SUCTION'	,'SUCTION' , 'SUCTION', '{}', 0, 99001);

INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'ELITE'	,'ELITE' , 'ELITE', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'INFINITY'	,'INFINITY' , 'INFINITY', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'NOBLE'	,'NOBLE' , 'NOBLE', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'KINGDOM'	,'KINGDOM' , 'KINGDOM', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'GOLDEN'	,'GOLDEN' , 'GOLDEN', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'PLATINUM'	,'PLATINUM' , 'PLATINUM', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'INKJET'	,'INKJET' , 'INKJET', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'DIGITAL'	,'DIGITAL' , 'DIGITAL', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'LOCAL'	,'LOCAL' , 'LOCAL', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'SANREMO'	,'SANREMO' , 'SANREMO', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'ECONOMIC'	,'ECONOMIC' , 'ECONOMIC', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'SPACE'	,'SPACE' , 'SPACE', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'VALENTINO'	,'VALENTINO' , 'VALENTINO', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'LUX'	,'LUX' , 'LUX', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'THERMOSTAT'	,'THERMOSTAT' , 'THERMOSTAT', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'AVANCE'	,'AVANCE' , 'AVANCE', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'frontalis'	,'frontalis' , 'frontalis', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'CONCA'	,'CONCA' , 'CONCA', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'KIMERA'	,'KIMERA' , 'KIMERA', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'TONIC'	,'TONIC' , 'TONIC', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'SOPHIA'	,'SOPHIA' , 'SOPHIA', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'MANTA'	,'MANTA' , 'MANTA', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'CAPRI'	,'CAPRI' , 'CAPRI', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'SUPER'	,'SUPER' , 'SUPER', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'PLAN'	,'PLAN' , 'PLAN', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'PLAYA'	,'PLAYA' , 'PLAYA', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'CONNECT'	,'CONNECT' , 'CONNECT', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'DIAGONAL'	,'DIAGONAL' , 'DIAGONAL', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'MIX'	,'MIX' , 'MIX', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'SLIMLINE'	,'SLIMLINE' , 'SLIMLINE', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'SHWER SIT'	,'SHWER SIT' , 'SHWER SIT', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'SHOWER SIT'	,'SHOWER SIT' , 'SHOWER SIT', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'IDYLL'	,'IDYLL' , 'IDYLL', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'CIRCLE'	,'CIRCLE' , 'CIRCLE', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'STUDIO'	,'STUDIO' , 'STUDIO', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'CERATHERM'	,'CERATHERM' , 'CERATHERM', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'GRANDERA'	,'GRANDERA' , 'GRANDERA', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'EURO CUBE'	,'EURO CUBE' , 'EURO CUBE', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'EURO SMART'	,'EURO SMART' , 'EURO SMART', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'CONSHETO'	,'CONSHETO' , 'CONSHETO', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'QUADRA'	,'QUADRA' , 'QUADRA', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'RAIN SHOWER'	,'RAIN SHOWER' , 'RAIN SHOWER', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'EURO DISK'	,'EURO DISK' , 'EURO DISK', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'BOW CLASSIC'	,'BOW CLASSIC' , 'BOW CLASSIC', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'BOWER&SOUL'	,'BOWER&SOUL' , 'BOWER&SOUL', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'ELYOUR'	,'ELYOUR' , 'ELYOUR', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'UFORIA CUBE'	,'UFORIA CUBE' , 'UFORIA CUBE', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'ESANS'	,'ESANS' , 'ESANS', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'KOZMO'	,'KOZMO' , 'KOZMO', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'DIGITAL2'	,'DIGITAL2' , 'DIGITAL2', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'DIGITAL3'	,'DIGITAL3' , 'DIGITAL3', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'DIGITAL1'	,'DIGITAL1' , 'DIGITAL1', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'UNIVRSL'	,'UNIVRSL' , 'UNIVRSL', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'DIAMANTE EVO'	,'DIAMANTE EVO' , 'DIAMANTE EVO', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'VULVE'	,'VULVE' , 'VULVE', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'EUROSTORM'	,'EUROSTORM' , 'EUROSTORM', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'MENTA'	,'MENTA' , 'MENTA', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'EURO STYLE'	,'EURO STYLE' , 'EURO STYLE', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'RUSTIC'	,'RUSTIC' , 'RUSTIC', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'COSTA'	,'COSTA' , 'COSTA', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'UFORIA'	,'UFORIA' , 'UFORIA', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'TEMPESTA'	,'TEMPESTA' , 'TEMPESTA', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'ZEDAR'	,'ZEDAR' , 'ZEDAR', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'PHARES'	,'PHARES' , 'PHARES', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'EURO PLUS'	,'EURO PLUS' , 'EURO PLUS', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'GET RAIN'	,'GET RAIN' , 'GET RAIN', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'NOUVA'	,'NOUVA' , 'NOUVA', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'EURO ECO'	,'EURO ECO' , 'EURO ECO', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'K FOUR'	,'K FOUR' , 'K FOUR', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'GET RELAXE'	,'GET RELAXE' , 'GET RELAXE', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'RELAXE PLUS'	,'RELAXE PLUS' , 'RELAXE PLUS', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'SIMPHONYA'	,'SIMPHONYA' , 'SIMPHONYA', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'SURF'	,'SURF' , 'SURF', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'LIMESTONE'	,'LIMESTONE' , 'LIMESTONE', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'ARENA'	,'ARENA' , 'ARENA', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'ATRYO'	,'ATRYO' , 'ATRYO', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'BIO CRAF'	,'BIO CRAF' , 'BIO CRAF', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'K SEVEN'	,'K SEVEN' , 'K SEVEN', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'TNSO'	,'TNSO' , 'TNSO', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'CIARA'	,'CIARA' , 'CIARA', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'BOW LOOP'	,'BOW LOOP' , 'BOW LOOP', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'individuals'	,'individuals' , 'individuals', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'R.DANS'	,'R.DANS' , 'R.DANS', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'MATRES'	,'MATRES' , 'MATRES', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'SHOWER HEADS'	,'SHOWER HEADS' , 'SHOWER HEADS', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'SPOTV'	,'SPOTV' , 'SPOTV', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'ECOS'	,'ECOS' , 'ECOS', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'MAJESTY'	,'MAJESTY' , 'MAJESTY', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'ECHO'	,'ECHO' , 'ECHO', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'MODUS'	,'MODUS' , 'MODUS', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'DEDRA'	,'DEDRA' , 'DEDRA', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'GINGO'	,'GINGO' , 'GINGO', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'ACCROY'	,'ACCROY' , 'ACCROY', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'M.ANGELO'	,'M.ANGELO' , 'M.ANGELO', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'VENICE'	,'VENICE' , 'VENICE', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'ESEDRA'	,'ESEDRA' , 'ESEDRA', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'TREND'	,'TREND' , 'TREND', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'CERAPLUS'	,'CERAPLUS' , 'CERAPLUS', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'CERAPLAN'	,'CERAPLAN' , 'CERAPLAN', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'ACTIVE'	,'ACTIVE' , 'ACTIVE', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'RETTA'	,'RETTA' , 'RETTA', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'NORA'	,'NORA' , 'NORA', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'SEVA M'	,'SEVA M' , 'SEVA M', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'SMART'	,'SMART' , 'SMART', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'CONCEPT 200'	,'CONCEPT 200' , 'CONCEPT 200', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'HERITAGE'	,'HERITAGE' , 'HERITAGE', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'BOW EDGE'	,'BOW EDGE' , 'BOW EDGE', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'SOLO'	,'SOLO' , 'SOLO', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'ICON'	,'ICON' , 'ICON', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'LINEAR'	,'LINEAR' , 'LINEAR', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'GRAND'	,'GRAND' , 'GRAND', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'ELEGANCE'	,'ELEGANCE' , 'ELEGANCE', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'HOTEL''S'	,'HOTEL''S' , 'HOTEL''S', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'FASHION'	,'FASHION' , 'FASHION', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'TWIN'	,'TWIN' , 'TWIN', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'VENETO'	,'VENETO' , 'VENETO', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'MAESTRO'	,'MAESTRO' , 'MAESTRO', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'SELECT'	,'SELECT' , 'SELECT', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'L90'	,'L90' , 'L90', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'PICASSO'	,'PICASSO' , 'PICASSO', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'KARREE'	,'KARREE' , 'KARREE', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'D-CODE'	,'D-CODE' , 'D-CODE', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'SALLAB'	,'SALLAB' , 'SALLAB', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'CUBICA'	,'CUBICA' , 'CUBICA', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'VICTORIA'	,'VICTORIA' , 'VICTORIA', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'SUPERINOX'	,'SUPERINOX' , 'SUPERINOX', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'RUBIC'	,'RUBIC' , 'RUBIC', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'ICE'	,'ICE' , 'ICE', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'SAND STONE'	,'SAND STONE' , 'SAND STONE', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'REDONDO'	,'REDONDO' , 'REDONDO', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'SERIES'	,'SERIES' , 'SERIES', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'CHEF2'	,'CHEF2' , 'CHEF2', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'PUZZLE'	,'PUZZLE' , 'PUZZLE', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'Sgur'	,'Sgur' , 'Sgur', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'MSTA'	,'MSTA' , 'MSTA', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'SCALA'	,'SCALA' , 'SCALA', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'Drnc'	,'Drnc' , 'Drnc', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'Klem'	,'Klem' , 'Klem', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'TARA'	,'TARA' , 'TARA', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'Lore'	,'Lore' , 'Lore', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'Kura'	,'Kura' , 'Kura', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'KLEX'	,'KLEX' , 'KLEX', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'RAYO'	,'RAYO' , 'RAYO', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'SLEN'	,'SLEN' , 'SLEN', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'DRON'	,'DRON' , 'DRON', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'NRMD'	,'NRMD' , 'NRMD', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'KLEK'	,'KLEK' , 'KLEK', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'O'	,'O' , 'O', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'LOFT'	,'LOFT' , 'LOFT', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'LOGS'	,'LOGS' , 'LOGS', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'TALIS C'	,'TALIS C' , 'TALIS C', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'dama senso'	,'dama senso' , 'dama senso', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'RAINDREAM'	,'RAINDREAM' , 'RAINDREAM', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'STRADA'	,'STRADA' , 'STRADA', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'FOCS E2'	,'FOCS E2' , 'FOCS E2', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'TALIS S2'	,'TALIS S2' , 'TALIS S2', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'CORM'	,'CORM' , 'CORM', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'KOMBIFIX'	,'KOMBIFIX' , 'KOMBIFIX', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'BORA'	,'BORA' , 'BORA', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'MATRES C'	,'MATRES C' , 'MATRES C', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'DELTA'	,'DELTA' , 'DELTA', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'PORV'	,'PORV' , 'PORV', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'METRO S'	,'METRO S' , 'METRO S', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'TALIS S'	,'TALIS S' , 'TALIS S', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'FOCS S'	,'FOCS S' , 'FOCS S', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'MATRES S'	,'MATRES S' , 'MATRES S', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'TALIS E'	,'TALIS E' , 'TALIS E', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'TALIS E2'	,'TALIS E2' , 'TALIS E2', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'siza'	,'siza' , 'siza', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'meridian'	,'meridian' , 'meridian', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'giralda'	,'giralda' , 'giralda', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'CORMT'	,'CORMT' , 'CORMT', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'FOCS E'	,'FOCS E' , 'FOCS E', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'CLASSIC'	,'CLASSIC' , 'CLASSIC', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'STST'	,'STST' , 'STST', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'FLORENTINA'	,'FLORENTINA' , 'FLORENTINA', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'ATLAS'	,'ATLAS' , 'ATLAS', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'MOAI'	,'MOAI' , 'MOAI', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'THESIS'	,'THESIS' , 'THESIS', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'TARGA'	,'TARGA' , 'TARGA', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'ESMAI'	,'ESMAI' , 'ESMAI', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'M2'	,'M2' , 'M2', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'LOFT ELITE'	,'LOFT ELITE' , 'LOFT ELITE', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'LOGICA'	,'LOGICA' , 'LOGICA', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'GANTE'	,'GANTE' , 'GANTE', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'NEOS II'	,'NEOS II' , 'NEOS II', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'ESSENTIAL'	,'ESSENTIAL' , 'ESSENTIAL', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'EVOLUTION'	,'EVOLUTION' , 'EVOLUTION', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'EVENT'	,'EVENT' , 'EVENT', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'SPOUTS'	,'SPOUTS' , 'SPOUTS', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'MONODIN'	,'MONODIN' , 'MONODIN', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'L20'	,'L20' , 'L20', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'WALL SPOUT'	,'WALL SPOUT' , 'WALL SPOUT', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'WALL JETS'	,'WALL JETS' , 'WALL JETS', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'URBAN'	,'URBAN' , 'URBAN', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'METRO E'	,'METRO E' , 'METRO E', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'MATRES E'	,'MATRES E' , 'MATRES E', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'SANTO'	,'SANTO' , 'SANTO', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'SINGLES'	,'SINGLES' , 'SINGLES', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'BARCELONA'	,'BARCELONA' , 'BARCELONA', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'RAINSENSE'	,'RAINSENSE' , 'RAINSENSE', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'EVOL'	,'EVOL' , 'EVOL', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'FOCS'	,'FOCS' , 'FOCS', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'AVEST'	,'AVEST' , 'AVEST', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'SINGLE OPEN'	,'SINGLE OPEN' , 'SINGLE OPEN', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'khroma'	,'khroma' , 'khroma', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'DEA'	,'DEA' , 'DEA', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'GAP'	,'GAP' , 'GAP', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'EGEO'	,'EGEO' , 'EGEO', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'MEGANE'	,'MEGANE' , 'MEGANE', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'MUSA'	,'MUSA' , 'MUSA', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'CAYEN'	,'CAYEN' , 'CAYEN', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'TOLOMEO'	,'TOLOMEO' , 'TOLOMEO', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'DELIZIA'	,'DELIZIA' , 'DELIZIA', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'LUCE'	,'LUCE' , 'LUCE', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'BRERA'	,'BRERA' , 'BRERA', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'MORGAN'	,'MORGAN' , 'MORGAN', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'LYBRADUE'	,'LYBRADUE' , 'LYBRADUE', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'MOCCA'	,'MOCCA' , 'MOCCA', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'AVERE'	,'AVERE' , 'AVERE', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'TREN'	,'TREN' , 'TREN', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'DURA'	,'DURA' , 'DURA', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'KMBOX'	,'KMBOX' , 'KMBOX', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'MNTG'	,'MNTG' , 'MNTG', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'KOI'	,'KOI' , 'KOI', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'FELORA'	,'FELORA' , 'FELORA', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'SFERO'	,'SFERO' , 'SFERO', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'SNTRINO'	,'SNTRINO' , 'SNTRINO', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'LAVADOR'	,'LAVADOR' , 'LAVADOR', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'ALASKA'	,'ALASKA' , 'ALASKA', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'FLORANS'	,'FLORANS' , 'FLORANS', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'OPTIMA'	,'OPTIMA' , 'OPTIMA', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'PALMERA'	,'PALMERA' , 'PALMERA', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'MADINTY'	,'MADINTY' , 'MADINTY', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'DREAM'	,'DREAM' , 'DREAM', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'VIOLA'	,'VIOLA' , 'VIOLA', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'TRESA'	,'TRESA' , 'TRESA', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'PURAFIDA'	,'PURAFIDA' , 'PURAFIDA', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'REVIRA'	,'REVIRA' , 'REVIRA', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'LORA'	,'LORA' , 'LORA', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'LAVI'	,'LAVI' , 'LAVI', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'FOTOSEL'	,'FOTOSEL' , 'FOTOSEL', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'REMORA'	,'REMORA' , 'REMORA', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'PALERMO'	,'PALERMO' , 'PALERMO', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'ALORA'	,'ALORA' , 'ALORA', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'CHARLOT'	,'CHARLOT' , 'CHARLOT', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'SLIM'	,'SLIM' , 'SLIM', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'TENNIS'	,'TENNIS' , 'TENNIS', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'LONZ'	,'LONZ' , 'LONZ', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'ASARO'	,'ASARO' , 'ASARO', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'LOSERN'	,'LOSERN' , 'LOSERN', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'Trnt'	,'Trnt' , 'Trnt', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'RIA'	,'RIA' , 'RIA', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'SALINA'	,'SALINA' , 'SALINA', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'ISIS'	,'ISIS' , 'ISIS', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'RIVER'	,'RIVER' , 'RIVER', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'OVAL'	,'OVAL' , 'OVAL', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'CERAMIX'	,'CERAMIX' , 'CERAMIX', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'CERALIFT'	,'CERALIFT' , 'CERALIFT', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'AZIMUTH'	,'AZIMUTH' , 'AZIMUTH', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'KENORA'	,'KENORA' , 'KENORA', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'CERAFLEX'	,'CERAFLEX' , 'CERAFLEX', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'COKY'	,'COKY' , 'COKY', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'KENORA PLUS'	,'KENORA PLUS' , 'KENORA PLUS', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'EUROPA'	,'EUROPA' , 'EUROPA', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'SHOWERS'	,'SHOWERS' , 'SHOWERS', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'CERAFIT'	,'CERAFIT' , 'CERAFIT', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'NEWWAVE'	,'NEWWAVE' , 'NEWWAVE', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'INDPNDNT'	,'INDPNDNT' , 'INDPNDNT', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'OVLUX'	,'OVLUX' , 'OVLUX', '{}', 0, 99001);

INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'WALL'	,'WALL' , 'WALL', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'TAPLUEX'	,'TAPLUEX' , 'TAPLUEX', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'SINGLE'	,'SINGLE' , 'SINGLE', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'null'	,'null' , 'null', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'LISTELLO'	,'LISTELLO' , 'LISTELLO', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'SHCE'	,'SHCE' , 'SHCE', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'HANGED PEDESTAL'	,'HANGED PEDESTAL' , 'HANGED PEDESTAL', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'WHIRLPOOL'	,'WHIRLPOOL' , 'WHIRLPOOL', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'URINAL PARTITION'	,'URINAL PARTITION' , 'URINAL PARTITION', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'PEDESTAL'	,'PEDESTAL' , 'PEDESTAL', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'GRANITE'	,'GRANITE' , 'GRANITE', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'STAINLESS STEEL'	,'STAINLESS STEEL' , 'STAINLESS STEEL', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'flush valve'	,'flush valve' , 'flush valve', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'WALL&FLOOR'	,'WALL&FLOOR' , 'WALL&FLOOR', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'TANK'	,'TANK' , 'TANK', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'SHOWER TRAY'	,'SHOWER TRAY' , 'SHOWER TRAY', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'BATH MIXER'	,'BATH MIXER' , 'BATH MIXER', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'MARBLE BASIN'	,'MARBLE BASIN' , 'MARBLE BASIN', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'WITH PANEL'	,'WITH PANEL' , 'WITH PANEL', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'FLOOR STANDING'	,'FLOOR STANDING' , 'FLOOR STANDING', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'METAL BATHTUB'	,'METAL BATHTUB' , 'METAL BATHTUB', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'SHEET'	,'SHEET' , 'SHEET', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'TOILET SEAT&COVER'	,'TOILET SEAT&COVER' , 'TOILET SEAT&COVER', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'BASIN MIXER'	,'BASIN MIXER' , 'BASIN MIXER', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'TOILET'	,'TOILET' , 'TOILET', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'SHOWER HEAD'	,'SHOWER HEAD' , 'SHOWER HEAD', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'COUNTERTOP'	,'COUNTERTOP' , 'COUNTERTOP', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'VANITY UNIT'	,'VANITY UNIT' , 'VANITY UNIT', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'WALL HANGED'	,'WALL HANGED' , 'WALL HANGED', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'BACK TO WALL'	,'BACK TO WALL' , 'BACK TO WALL', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'SEMI COUNTER'	,'SEMI COUNTER' , 'SEMI COUNTER', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'WASHBASIN'	,'WASHBASIN' , 'WASHBASIN', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'OVER COUNTER'	,'OVER COUNTER' , 'OVER COUNTER', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'SOAP HOLDER'	,'SOAP HOLDER' , 'SOAP HOLDER', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'HANDLE'	,'HANDLE' , 'HANDLE', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'BACKREST'	,'BACKREST' , 'BACKREST', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'SECTION'	,'SECTION' , 'SECTION', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'TRAY DOOR'	,'TRAY DOOR' , 'TRAY DOOR', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'KITCHEN MIXER'	,'KITCHEN MIXER' , 'KITCHEN MIXER', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'PANEL'	,'PANEL' , 'PANEL', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'UNDER COUNTER'	,'UNDER COUNTER' , 'UNDER COUNTER', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'TANK COVER'	,'TANK COVER' , 'TANK COVER', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'TOWEL HOLDER'	,'TOWEL HOLDER' , 'TOWEL HOLDER', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'FIXED SHEET'	,'FIXED SHEET' , 'FIXED SHEET', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'ANGEL VALVE'	,'ANGEL VALVE' , 'ANGEL VALVE', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'PAPER HOLDER'	,'PAPER HOLDER' , 'PAPER HOLDER', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'DISPENSER'	,'DISPENSER' , 'DISPENSER', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'TOWEL RING'	,'TOWEL RING' , 'TOWEL RING', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'HOOK'	,'HOOK' , 'HOOK', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'SPOUT'	,'SPOUT' , 'SPOUT', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'SHOWER ARM'	,'SHOWER ARM' , 'SHOWER ARM', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'CUP HOLDER'	,'CUP HOLDER' , 'CUP HOLDER', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'BIDET MIXER'	,'BIDET MIXER' , 'BIDET MIXER', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'SHOWER HAND'	,'SHOWER HAND' , 'SHOWER HAND', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'PLATES'	,'PLATES' , 'PLATES', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'FURNITURE BASIN'	,'FURNITURE BASIN' , 'FURNITURE BASIN', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'KOMPI'	,'KOMPI' , 'KOMPI', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'SHATTAF'	,'SHATTAF' , 'SHATTAF', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'BRUSH'	,'BRUSH' , 'BRUSH', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'SHELF'	,'SHELF' , 'SHELF', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'MIRROR'	,'MIRROR' , 'MIRROR', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'HANDGRIPS'	,'HANDGRIPS' , 'HANDGRIPS', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'INSTANT HEATER'	,'INSTANT HEATER' , 'INSTANT HEATER', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'BUILT IN OUT LET'	,'BUILT IN OUT LET' , 'BUILT IN OUT LET', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'BUILT IN VALVE'	,'BUILT IN VALVE' , 'BUILT IN VALVE', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'JET'	,'JET' , 'JET', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'LAY'	,'LAY' , 'LAY', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'TRAP'	,'TRAP' , 'TRAP', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'SHOWER'	,'SHOWER' , 'SHOWER', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'DRYER'	,'DRYER' , 'DRYER', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'FASTENING SET'	,'FASTENING SET' , 'FASTENING SET', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'VALVE COVER'	,'VALVE COVER' , 'VALVE COVER', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'LAP MIXER'	,'LAP MIXER' , 'LAP MIXER', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'HEADREST'	,'HEADREST' , 'HEADREST', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'ACIDS RESISTANT'	,'ACIDS RESISTANT' , 'ACIDS RESISTANT', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'BASKET'	,'BASKET' , 'BASKET', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'SHOWER FLOOR'	,'SHOWER FLOOR' , 'SHOWER FLOOR', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'SHOWER UNIT'	,'SHOWER UNIT' , 'SHOWER UNIT', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'BATHTUB PINS'	,'BATHTUB PINS' , 'BATHTUB PINS', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'CAPULI'	,'CAPULI' , 'CAPULI', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'DOU.HOOK'	,'DOU.HOOK' , 'DOU.HOOK', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'POP UP'	,'POP UP' , 'POP UP', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'GRINDER'	,'GRINDER' , 'GRINDER', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'S.H.B'	,'S.H.B' , 'S.H.B', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'CERAMICS'	,'CERAMICS' , 'CERAMICS', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'ARM'	,'ARM' , 'ARM', '{}', 0, 99001);
INSERT INTO public.tags (category_id, "name", alias, p_name, metadata, removed, organization_id) VALUES(233, 'HEIGHT'	,'HEIGHT' , 'HEIGHT', '{}', 0, 99001);