INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'GEMMA', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'ROYAL', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'INNOVA', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'SALLABCO', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'PRIMA', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'DURAVIT', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'TIB', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'IDEAL STANDARD', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'MASR ACRYLIC', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'ROCA', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'HANS GROHE', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'CERPA', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'RYLONDA', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'CLEOPATRA', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'SANY ACRLIC', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'GROHE', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'ZS', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'BEROIA', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'REMAS', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'TULIP', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'LECICO', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'KALLY', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'DUNE', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'ART', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'ZED', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'DFINESS', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'SARRAGUEMIN', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'Granito', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'GLORIA', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'DIAMOND ROCK', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'MURANO', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'ATLANTIC', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'HANS', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'ARCANA', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'Baoding', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'Aparici', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'NEWKER', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'KOHLER', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'ALFA', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'ATLAS CONCORDE', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'PORCELLAN', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'SSWW', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'IMAGE', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'VALENCIA', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'ARASEMCO', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'MOSAVIT', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'SARR DESIGN', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'GWAD', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'FRANKE', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'JOYU', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'MATERIAL', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'COLORKER', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'HONG YU', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'VENUS', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'CONI', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'PRIME GROUP', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'FILLI FRATTINI', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'ROMARIO', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'ALTO GLASS', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'MIJARES', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'MARAZZI', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'APE', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'AL-AMAN', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'KITCHEN STUDIO', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'WD', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'DREAM TILE', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'yekalon', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'INTERHASA', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'LIMESTONE', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'VAMA', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'LANGDENG', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'CERA', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'TAU', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'GEOTILES', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'ARGENTA', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'CICOGRES', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'ECOCERAMIC', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'kito', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'LA FABBRICA', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'LOSDI', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'REDRING', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'AOXIN', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'Avilados', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'Gazella', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'Vivo', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'UKINOX', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'PELI PARQUET', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'WOMA', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'PORCELANITE DOS', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'ASFOUR CRYSTAL', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'Glass Design', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'OSET', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'VIEWGRES', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'LANKEE', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'BATHCO', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'WIDING', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'ALAPLANA', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'MEXDA', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'LUIS VALENTINO', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'REGALIA', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'GRAVENA', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'ONIX', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'RUBEX', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'MAINZU', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'ABK', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'HDC', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'FLORINA', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'SIEMENS', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'KERABEN', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'MMT-STONE', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'HUIDA', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'GAYAFORES', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'PLATERA', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'PLAZA', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'TERCOCER', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'SEM', now(), now(), 99001);
INSERT INTO public.brands(category_id, name,created_at, updated_at, organization_id) VALUES ( 201, 'KLUDI', now(), now(), 99001);