--liquibase formatted sql

--changeset Ashraf:employee_user_heart_beats_logs dbms:postgresql splitStatements:false failOnError:true

--comment: add employee_user_heart_beats_logs

create table if not exists public.employee_user_heart_beats_logs
(
    id               bigint generated by default as identity,
    created_at       timestamp,
    employee_user_id bigint not null,
    constraint employee_user_heart_beats_logs_pkey primary key (id),
    constraint employee_user_id_unique unique (employee_user_id),
    constraint employee_user_heart_beats_logs_user_fk foreign key (employee_user_id) references public.employee_users
);

