create table if not exists public.employee_user_heart_beats_logs
(
    id         bigint generated by default as identity
        constraint employee_user_heart_beats_logs_pkey
            primary key,
    created_at timestamp,
    employee_user_id    bigint
        constraint employee_user_heart_beats_logs_user_fk
            references public.employee_users
);

