--liquibase formatted sql

--changeset Ashraf:add_advertisements dbms:postgresql splitStatements:false failOnError:true

--comment: add advertisements

create table if not exists public.advertisements
(
    id         bigint generated by default as identity primary key,
    coins      integer,
    created_at timestamp,
    from_date timestamp,
    to_date timestamp,
    likes      integer,
    product_id bigint not null constraint advertisements_product_fk references public.products
);
alter table public.posts
    add column if not exists advertisement_id bigint constraint posts_advertisements_fk references public.advertisements;