--liquibase formatted sql

--changeset Ashraf:advertisement_product dbms:postgresql splitStatements:false failOnError:true

--comment: add advertisement_product

create table if not exists public.advertisement_product
(
    id               bigint generated by default as identity primary key,
    coins            integer,
    likes            integer,
    product_id       bigint not null
        constraint advertisement_product_product_fk references public.products,
    advertisement_id bigint not null
        constraint advertisement_product_advertisement_fk references public.advertisements
);


alter table public.advertisements
    drop column if exists product_id;
alter table public.advertisements
    drop column if exists coins;
alter table public.advertisements
    drop column if exists likes;


alter table public.advertisements
    drop column if exists banner_url;
alter table public.advertisements
    drop column if exists organization_id;



alter table advertisements
    add column banner_url varchar(350);


alter table advertisements
    add column organization_id bigint;
alter table advertisements
    add constraint advertisements_organization_fk
        foreign key (organization_id) references organizations;
