--liquibase formatted sql

--changeset Ashraf:add_advertisements dbms:postgresql splitStatements:false failOnError:true

--comment: add advertisements

create table if not exists public.advertisements
(
    id         bigint generated by default as identity primary key,
    coins      integer,
    created_at timestamp,
    likes      integer,
    max_coins  integer not null,
    product_id bigint not null constraint fkr9piq7lhox1d2ha3jn316dtux references public.products
);
alter table public.posts
    add column if not exists advertisement_id bigint constraint fka8rolgxvgid0mv3bu3aijlfgu references public.advertisements;