--liquibase formatted sql

--changeset Moamen:Generate_Sub_Post_Table dbms:postgresql splitStatements:true failOnError:true


CREATE TABLE sub_posts (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   post_id BIGINT,
   product_id BIGINT,
   CONSTRAINT pk_sub_posts PRIMARY KEY (id)
);

ALTER TABLE sub_posts ADD CONSTRAINT FK_SUB_POSTS_ON_POST FOREIGN KEY (post_id) REFERENCES posts (id);

ALTER TABLE sub_posts ADD CONSTRAINT FK_SUB_POSTS_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE post_likes ADD COLUMN sub_post_id BIGINT;
ALTER TABLE post_likes ADD CONSTRAINT FK_POST_LIKES_ON_SUB_POST FOREIGN KEY (sub_post_id) REFERENCES sub_posts (id);
