--liquibase formatted sql

--changeset Moamen:Compensation_Table dbms:postgresql splitStatements:true failOnError:true


-- Table for different types of actions
CREATE TABLE compensation_action (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) UNIQUE,
  description VARCHAR(255)
);

-- Table for compensation rules
CREATE TABLE compensation_rules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  action_id BIGINT NOT NULL,
  organization_id BIGINT NOT NULL,
  is_active BOOLEAN DEFAULT TRUE NOT NULL,
  FOREIGN KEY (action_id) REFERENCES compensation_action(id),
  FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT uc_action_organization_unique UNIQUE (action_id, organization_id)
);



CREATE TABLE compensation_rule_tier (
  id BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
  condition BIGINT NOT NULL,
  reward numeric DEFAULT 0 NOT NULL,
  is_active BOOLEAN DEFAULT TRUE NOT NULL,
  rule_id BIGINT NOT NULL REFERENCES compensation_rules (id),
  CONSTRAINT uc_condition_rule_unique UNIQUE (condition, rule_id, is_active)

);


