--liquibase formatted sql

--changeset Moamen:advertisement_product_compensation splitStatements:true failOnError:true


CREATE TABLE advertisement_product_compensation (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   advertisement_product_id BIGINT NOT NULL,
   compensation_rule BIGINT NOT NULL,
   CONSTRAINT pk_advertisement_product_compensation PRIMARY KEY (id)
);

ALTER TABLE advertisement_product_compensation ADD CONSTRAINT FK_ADVERTISEMENT_PRODUCT_COMPENSATION_ON_ADVERTISEMENT_PRODUCT FOREIGN KEY (advertisement_product_id) REFERENCES advertisement_product (id);

ALTER TABLE advertisement_product_compensation ADD CONSTRAINT FK_ADVERTISEMENT_PRODUCT_COMPENSATION_ON_COMPENSATION_RULE FOREIGN KEY (compensation_rule) REFERENCES compensation_rules (id);
